# Generated by Django 5.0.4 on 2024-05-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
