# Generated by Django 5.0.4 on 2024-05-03 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_follower_follower_alter_follower_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='user',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='follower',
            old_name='follower',
            new_name='to_user',
        ),
    ]
