# Generated by Django 5.0.4 on 2024-05-03 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_to_user_follower_followers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='followers',
            new_name='follower',
        ),
    ]
